In [1]:
#Library
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
# importing module
import warnings
# of the warnings filter.
warnings.filterwarnings('ignore')

In [2]:
train=pd.read_csv("train.csv")
test=pd.read_csv("test.csv")

In [3]:
#Descriptive Analysis
train.head()

Id      v2a1  hacdor  rooms  hacapo  v14a  refrig  v18q  v18q1  \
0  ID_279628684  190000.0       0      3       0     1       1     0    NaN   
1  ID_f29eb3ddd  135000.0       0      4       0     1       1     1    1.0   
2  ID_68de51c94       NaN       0      8       0     1       1     0    NaN   
3  ID_d671db89c  180000.0       0      5       0     1       1     1    1.0   
4  ID_d56d6f5f5  180000.0       0      5       0     1       1     1    1.0   

   r4h1  ...  SQBescolari  SQBage  SQBhogar_total  SQBedjefe  SQBhogar_nin  \
0     0  ...          100    1849               1        100             0   
1     0  ...          144    4489               1        144             0   
2     0  ...          121    8464               1          0             0   
3     0  ...           81     289              16        121             4   
4     0  ...          121    1369              16        121             4   

   SQBovercrowding  SQBdependency  SQBmeaned  agesq  Target  
0         1.000000            0.0      100.0   1849       4  
1         1.000000           64.0      144.0   4489       4  
2         0.250000           64.0      121.0   8464       4  
3         1.777778            1.0      121.0    289       4  
4         1.777778            1.0      121.0   1369       4  

[5 rows x 143 columns]

In [4]:
test.head()

Id      v2a1  hacdor  rooms  hacapo  v14a  refrig  v18q  v18q1  \
0  ID_2f6873615       NaN       0      5       0     1       1     0    NaN   
1  ID_1c78846d2       NaN       0      5       0     1       1     0    NaN   
2  ID_e5442cf6a       NaN       0      5       0     1       1     0    NaN   
3  ID_a8db26a79       NaN       0     14       0     1       1     1    1.0   
4  ID_a62966799  175000.0       0      4       0     1       1     1    1.0   

   r4h1  ...  age  SQBescolari  SQBage  SQBhogar_total  SQBedjefe  \
0     1  ...    4            0      16               9          0   
1     1  ...   41          256    1681               9          0   
2     1  ...   41          289    1681               9          0   
3     0  ...   59          256    3481               1        256   
4     0  ...   18          121     324               1          0   

   SQBhogar_nin  SQBovercrowding  SQBdependency  SQBmeaned  agesq  
0             1             2.25           0.25     272.25     16  
1             1             2.25           0.25     272.25   1681  
2             1             2.25           0.25     272.25   1681  
3             0             1.00           0.00     256.00   3481  
4             1             0.25          64.00        NaN    324  

[5 rows x 142 columns]

In [5]:
train.describe()

v2a1       hacdor        rooms       hacapo         v14a  \
count  2.697000e+03  9557.000000  9557.000000  9557.000000  9557.000000   
mean   1.652316e+05     0.038087     4.955530     0.023648     0.994768   
std    1.504571e+05     0.191417     1.468381     0.151957     0.072145   
min    0.000000e+00     0.000000     1.000000     0.000000     0.000000   
25%    8.000000e+04     0.000000     4.000000     0.000000     1.000000   
50%    1.300000e+05     0.000000     5.000000     0.000000     1.000000   
75%    2.000000e+05     0.000000     6.000000     0.000000     1.000000   
max    2.353477e+06     1.000000    11.000000     1.000000     1.000000   

            refrig         v18q        v18q1         r4h1         r4h2  ...  \
count  9557.000000  9557.000000  2215.000000  9557.000000  9557.000000  ...   
mean      0.957623     0.231767     1.404063     0.385895     1.559171  ...   
std       0.201459     0.421983     0.763131     0.680779     1.036574  ...   
min       0.000000     0.000000     1.000000     0.000000     0.000000  ...   
25%       1.000000     0.000000     1.000000     0.000000     1.000000  ...   
50%       1.000000     0.000000     1.000000     0.000000     1.000000  ...   
75%       1.000000     0.000000     2.000000     1.000000     2.000000  ...   
max       1.000000     1.000000     6.000000     5.000000     8.000000  ...   

       SQBescolari       SQBage  SQBhogar_total    SQBedjefe  SQBhogar_nin  \
count  9557.000000  9557.000000     9557.000000  9557.000000   9557.000000   
mean     74.222769  1643.774302       19.132887    53.500262      3.844826   
std      76.777549  1741.197050       18.751395    78.445804      6.946296   
min       0.000000     0.000000        1.000000     0.000000      0.000000   
25%      16.000000   289.000000        9.000000     0.000000      0.000000   
50%      36.000000   961.000000       16.000000    36.000000      1.000000   
75%     121.000000  2601.000000       25.000000    81.000000      4.000000   
max     441.000000  9409.000000      169.000000   441.000000     81.000000   

       SQBovercrowding  SQBdependency    SQBmeaned        agesq       Target  
count      9557.000000    9557.000000  9552.000000  9557.000000  9557.000000  
mean          3.249485       3.900409   102.588867  1643.774302     3.302292  
std           4.129547      12.511831    93.516890  1741.197050     1.009565  
min           0.040000       0.000000     0.000000     0.000000     1.000000  
25%           1.000000       0.111111    36.000000   289.000000     3.000000  
50%           2.250000       0.444444    81.000000   961.000000     4.000000  
75%           4.000000       1.777778   134.560010  2601.000000     4.000000  
max          36.000000      64.000000  1369.000000  9409.000000     4.000000  

[8 rows x 138 columns]

In [6]:
test.describe()

v2a1        hacdor         rooms        hacapo          v14a  \
count  6.453000e+03  23856.000000  23856.000000  23856.000000  23856.000000   
mean   1.748726e+05      0.050679      4.955776      0.028421      0.992748   
std    1.567887e+05      0.219346      1.539753      0.166174      0.084850   
min    0.000000e+00      0.000000      1.000000      0.000000      0.000000   
25%    8.000000e+04      0.000000      4.000000      0.000000      1.000000   
50%    1.400000e+05      0.000000      5.000000      0.000000      1.000000   
75%    2.200000e+05      0.000000      6.000000      0.000000      1.000000   
max    2.852700e+06      1.000000     15.000000      1.000000      1.000000   

             refrig          v18q        v18q1          r4h1          r4h2  \
count  23856.000000  23856.000000  5730.000000  23856.000000  23856.000000   
mean       0.961603      0.240191     1.348517      0.416541      1.563967   
std        0.192157      0.427208     0.694216      0.713255      0.990171   
min        0.000000      0.000000     1.000000      0.000000      0.000000   
25%        1.000000      0.000000     1.000000      0.000000      1.000000   
50%        1.000000      0.000000     1.000000      0.000000      1.000000   
75%        1.000000      0.000000     1.750000      1.000000      2.000000   
max        1.000000      1.000000     6.000000      6.000000      7.000000   

       ...           age  SQBescolari        SQBage  SQBhogar_total  \
count  ...  23856.000000  23856.00000  23856.000000    23856.000000   
mean   ...     34.454183     74.44974   1657.798080       19.113389   
std    ...     21.696245     76.99701   1753.603406       17.314597   
min    ...      0.000000      0.00000      0.000000        1.000000   
25%    ...     16.000000     16.00000    256.000000        9.000000   
50%    ...     32.000000     36.00000   1024.000000       16.000000   
75%    ...     51.000000    121.00000   2601.000000       25.000000   
max    ...     97.000000    441.00000   9409.000000      169.000000   

          SQBedjefe  SQBhogar_nin  SQBovercrowding  SQBdependency  \
count  23856.000000  23856.000000     23856.000000   23856.000000   
mean      54.087232      3.885480         3.564751       4.171669   
std       77.312255      6.878967         6.668757      13.105989   
min        0.000000      0.000000         0.020408       0.000000   
25%        0.000000      0.000000         1.000000       0.111111   
50%       36.000000      1.000000         2.250000       0.444444   
75%       81.000000      4.000000         4.000000       1.777778   
max      441.000000    100.000000       169.000000      64.000000   

          SQBmeaned         agesq  
count  23825.000000  23856.000000  
mean     100.509220   1657.798080  
std       89.211063   1753.603406  
min        0.000000      0.000000  
25%       36.000000    256.000000  
50%       75.111115   1024.000000  
75%      132.250000   2601.000000  
max     1296.000000   9409.000000  

[8 rows x 137 columns]

In [7]:
train.columns

Index(['Id', 'v2a1', 'hacdor', 'rooms', 'hacapo', 'v14a', 'refrig', 'v18q',
       'v18q1', 'r4h1',
       ...
       'SQBescolari', 'SQBage', 'SQBhogar_total', 'SQBedjefe', 'SQBhogar_nin',
       'SQBovercrowding', 'SQBdependency', 'SQBmeaned', 'agesq', 'Target'],
      dtype='object', length=143)

In [8]:
test.columns

Index(['Id', 'v2a1', 'hacdor', 'rooms', 'hacapo', 'v14a', 'refrig', 'v18q',
       'v18q1', 'r4h1',
       ...
       'age', 'SQBescolari', 'SQBage', 'SQBhogar_total', 'SQBedjefe',
       'SQBhogar_nin', 'SQBovercrowding', 'SQBdependency', 'SQBmeaned',
       'agesq'],
      dtype='object', length=142)

In [9]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9557 entries, 0 to 9556
Columns: 143 entries, Id to Target
dtypes: float64(8), int64(130), object(5)
memory usage: 10.4+ MB


In [10]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23856 entries, 0 to 23855
Columns: 142 entries, Id to agesq
dtypes: float64(8), int64(129), object(5)
memory usage: 25.8+ MB


In [11]:
#UID is unique userID value in the train and test dataset. So an index can be created from the UID feature
train.set_index(keys=['Id'],inplace=True)  #Set the DataFrame index using existing columns.
id_test=test['Id']
test.set_index(keys=['Id'],inplace=True)

In [12]:
#Handling Missing value
train.isnull().sum()/len(train)*100

v2a1               71.779847
hacdor              0.000000
rooms               0.000000
hacapo              0.000000
v14a                0.000000
                     ...    
SQBovercrowding     0.000000
SQBdependency       0.000000
SQBmeaned           0.052318
agesq               0.000000
Target              0.000000
Length: 142, dtype: float64

In [13]:
train.columns[train.isnull().mean() > 0.2]

Index(['v2a1', 'v18q1', 'rez_esc'], dtype='object')

In [14]:
train=train.drop(['v2a1', 'v18q1', 'rez_esc'],axis=1)

In [15]:
train=train.dropna()

In [16]:
test.isnull().sum()/len(test)*100

v2a1               72.950201
hacdor              0.000000
rooms               0.000000
hacapo              0.000000
v14a                0.000000
                     ...    
SQBhogar_nin        0.000000
SQBovercrowding     0.000000
SQBdependency       0.000000
SQBmeaned           0.129946
agesq               0.000000
Length: 141, dtype: float64

In [17]:
test.columns[test.isnull().mean() > 0.2]

Index(['v2a1', 'v18q1', 'rez_esc'], dtype='object')

In [18]:
test=test.drop(['v2a1', 'v18q1', 'rez_esc'],axis=1)

In [19]:
test=test.dropna()

In [20]:
train.isnull().sum()/len(train)*100

hacdor             0.0
rooms              0.0
hacapo             0.0
v14a               0.0
refrig             0.0
                  ... 
SQBovercrowding    0.0
SQBdependency      0.0
SQBmeaned          0.0
agesq              0.0
Target             0.0
Length: 139, dtype: float64

In [21]:
test.isnull().sum()/len(test)*100

hacdor             0.0
rooms              0.0
hacapo             0.0
v14a               0.0
refrig             0.0
                  ... 
SQBhogar_nin       0.0
SQBovercrowding    0.0
SQBdependency      0.0
SQBmeaned          0.0
agesq              0.0
Length: 138, dtype: float64

In [22]:
obj_variable=list(train.select_dtypes(include=['object']).columns)

In [23]:
obj_variable

['idhogar', 'dependency', 'edjefe', 'edjefa']

In [24]:
#Label Encoding for object to numeric conversion
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for feat in obj_variable:
    train[feat] = le.fit_transform(train[feat].astype(str))

print (train.info())

<class 'pandas.core.frame.DataFrame'>
Index: 9552 entries, ID_279628684 to ID_a38c64491
Columns: 139 entries, hacdor to Target
dtypes: float64(5), int32(4), int64(130)
memory usage: 10.1+ MB
None


In [25]:
train.head()

hacdor  rooms  hacapo  v14a  refrig  v18q  r4h1  r4h2  r4h3  \
Id                                                                          
ID_279628684       0      3       0     1       1     0     0     1     1   
ID_f29eb3ddd       0      4       0     1       1     1     0     1     1   
ID_68de51c94       0      8       0     1       1     0     0     0     0   
ID_d671db89c       0      5       0     1       1     1     0     2     2   
ID_d56d6f5f5       0      5       0     1       1     1     0     2     2   

              r4m1  ...  SQBescolari  SQBage  SQBhogar_total  SQBedjefe  \
Id                  ...                                                   
ID_279628684     0  ...          100    1849               1        100   
ID_f29eb3ddd     0  ...          144    4489               1        144   
ID_68de51c94     0  ...          121    8464               1          0   
ID_d671db89c     1  ...           81     289              16        121   
ID_d56d6f5f5     1  ...          121    1369              16        121   

              SQBhogar_nin  SQBovercrowding  SQBdependency  SQBmeaned  agesq  \
Id                                                                             
ID_279628684             0         1.000000            0.0      100.0   1849   
ID_f29eb3ddd             0         1.000000           64.0      144.0   4489   
ID_68de51c94             0         0.250000           64.0      121.0   8464   
ID_d671db89c             4         1.777778            1.0      121.0    289   
ID_d56d6f5f5             4         1.777778            1.0      121.0   1369   

              Target  
Id                    
ID_279628684       4  
ID_f29eb3ddd       4  
ID_68de51c94       4  
ID_d671db89c       4  
ID_d56d6f5f5       4  

[5 rows x 139 columns]

In [26]:
for feat in obj_variable:
    test[feat] = le.fit_transform(test[feat].astype(str))

print (test.info())

<class 'pandas.core.frame.DataFrame'>
Index: 23825 entries, ID_2f6873615 to ID_34754556f
Columns: 138 entries, hacdor to agesq
dtypes: float64(5), int32(4), int64(129)
memory usage: 24.9+ MB
None


In [27]:
test.head()

hacdor  rooms  hacapo  v14a  refrig  v18q  r4h1  r4h2  r4h3  \
Id                                                                          
ID_2f6873615       0      5       0     1       1     0     1     1     2   
ID_1c78846d2       0      5       0     1       1     0     1     1     2   
ID_e5442cf6a       0      5       0     1       1     0     1     1     2   
ID_a8db26a79       0     14       0     1       1     1     0     1     1   
ID_e77d38d45       0      3       0     1       1     1     0     0     0   

              r4m1  ...  age  SQBescolari  SQBage  SQBhogar_total  SQBedjefe  \
Id                  ...                                                        
ID_2f6873615     0  ...    4            0      16               9          0   
ID_1c78846d2     0  ...   41          256    1681               9          0   
ID_e5442cf6a     0  ...   41          289    1681               9          0   
ID_a8db26a79     0  ...   59          256    3481               1        256   
ID_e77d38d45     0  ...   38          256    1444               4          0   

              SQBhogar_nin  SQBovercrowding  SQBdependency  SQBmeaned  agesq  
Id                                                                            
ID_2f6873615             1             2.25           0.25     272.25     16  
ID_1c78846d2             1             2.25           0.25     272.25   1681  
ID_e5442cf6a             1             2.25           0.25     272.25   1681  
ID_a8db26a79             0             1.00           0.00     256.00   3481  
ID_e77d38d45             0             1.00           0.00     182.25   1444  

[5 rows x 138 columns]

In [28]:
X=train.iloc[:,:-1].values
y=train.iloc[:,-1].values

In [29]:
# splitting X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,
                                                    random_state=1)

In [30]:
from sklearn.model_selection import cross_val_score
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators=600, max_depth=300, max_features='sqrt')
rfc.fit(X_train,y_train)
rfc_predict = rfc.predict(X_test)
scores = cross_val_score(rfc, X_train, y_train, cv=5)
print(scores)
print(metrics.accuracy_score(rfc_predict,y_test))

[0.87144993 0.88930441 0.90276739 0.87658938 0.87808527]
0.9117236566643405


In [31]:
from sklearn.metrics import classification_report, confusion_matrix
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, rfc_predict))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, rfc_predict))

=== Confusion Matrix ===
[[ 171   14    0   32]
 [   3  374    5   85]
 [   0   21  253   88]
 [   0    2    3 1815]]


=== Classification Report ===
              precision    recall  f1-score   support

           1       0.98      0.79      0.87       217
           2       0.91      0.80      0.85       467
           3       0.97      0.70      0.81       362
           4       0.90      1.00      0.95      1820

    accuracy                           0.91      2866
   macro avg       0.94      0.82      0.87      2866
weighted avg       0.92      0.91      0.91      2866



In [34]:
rcf=rfc.predict(test)
rcf

array([4, 4, 4, ..., 4, 4, 4], dtype=int64)